#!/usr/bin/env python3
"""
embed_patches.py - Generate embedded_patches.h from data/*.pd files

Scans the data/ folder of an Arduino sketch for .pd files and generates
a C header that embeds them as string constants. The sketch writes these
to LittleFS on boot so Pd.openPatch() can load any of them.

Usage:
    cd YourSketch/
    python3 ../../scripts/embed_patches.py

    Or from anywhere:
    python3 embed_patches.py path/to/SketchFolder/

The generated embedded_patches.h is placed in the sketch folder alongside
the .ino file.
"""

import os
import sys
import glob


def escape_for_c(text):
    """Escape a string for embedding in a C string literal."""
    result = []
    for line in text.splitlines():
        # Escape backslashes and double quotes
        line = line.replace('\\', '\\\\').replace('"', '\\"')
        result.append(f'    "{line}\\n"')
    return '\n'.join(result)


def varname_from_filename(filename):
    """Convert a filename to a valid C variable name."""
    name = os.path.splitext(filename)[0]
    name = name.replace('-', '_').replace(' ', '_').replace('.', '_')
    return 'PATCH_' + name.upper()


def generate_header(sketch_dir):
    data_dir = os.path.join(sketch_dir, 'data')
    if not os.path.isdir(data_dir):
        print(f"Error: no data/ folder found in {sketch_dir}")
        sys.exit(1)

    pd_files = sorted(glob.glob(os.path.join(data_dir, '*.pd')))
    if not pd_files:
        print(f"Error: no .pd files found in {data_dir}")
        sys.exit(1)

    lines = []
    lines.append('// Auto-generated by embed_patches.py — do not edit manually')
    lines.append('// Re-run: python3 ../../scripts/embed_patches.py')
    lines.append(f'// Source: data/ ({len(pd_files)} patch{"es" if len(pd_files) != 1 else ""})')
    lines.append('')
    lines.append('#ifndef EMBEDDED_PATCHES_H')
    lines.append('#define EMBEDDED_PATCHES_H')
    lines.append('')

    entries = []
    for pd_path in pd_files:
        filename = os.path.basename(pd_path)
        varname = varname_from_filename(filename)

        with open(pd_path, 'r') as f:
            content = f.read()

        lines.append(f'// {filename}')
        lines.append(f'static const char {varname}[] =')
        lines.append(escape_for_c(content) + ';')
        lines.append('')

        entries.append((filename, varname))

    # Generate the patch table
    lines.append('struct EmbeddedPatch { const char* name; const char* content; };')
    lines.append(f'static const EmbeddedPatch PATCHES[] = {{')
    for filename, varname in entries:
        lines.append(f'    {{ "{filename}", {varname} }},')
    lines.append('};')
    lines.append(f'static const int NUM_PATCHES = {len(entries)};')
    lines.append('')
    lines.append('#endif // EMBEDDED_PATCHES_H')
    lines.append('')

    output_path = os.path.join(sketch_dir, 'embedded_patches.h')
    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))

    print(f"Generated {output_path}")
    for filename, _ in entries:
        print(f"  - {filename}")


if __name__ == '__main__':
    if len(sys.argv) > 1:
        sketch_dir = sys.argv[1]
    else:
        sketch_dir = os.getcwd()

    generate_header(sketch_dir)
